export enum Commands {
  // Base Commands
  GET_WALLET_SUMMARY = "Get Wallet Summary",
  INITIALIZE_EMBEDDED_WALLET = "Initialize Embedded Wallet",
  INITIALIZE_CORE_NCW = "Initialize Core NCW",
  REFRESH_IDP_TOKEN = "Refresh Idp Token",
  SET_CUSTOM_PRINCIPAL_CLAIM = "Set Custom Principal Claim",
  GET_CUSTOM_PRINCIPAL_CLAIM = "Get Custom Principal Claim",

  // Core Commands
  APPROVE_JOIN_WALLET_REQUEST = "Approve Join Wallet Request",
  REQUEST_JOIN_EXISTING_WALLET = "Request Join Existing Wallet",
  STOP_JOIN_WALLET = "Stop Join Wallet",
  TAKEOVER = "Takeover",
  BACKUP_KEYS = "Backup Keys",
  RECOVER_KEYS = "Recover Keys",
  GENERATE_MPC_KEYS = "Generate MPC Keys",
  DERIVE_ASSET_KEY = "Derive Asset Key",
  GET_KEYS_STATUS = "Get Keys Status",
  STOP_MPC_DEVICE_SETUP = "Stop MPC Device Setup",
  SIGN_TRANSACTION = "Sign Transaction",
  STOP_IN_PROGRESS_SIGN_TRANSACTION = "Stop In Progress Sign Transaction",
  GET_IN_PROGRESS_SIGNING_TX_ID = "Get In Progress Signing Tx ID",
  CLEAR_ALL_STORAGE = "Clear All Storage",
  DISPOSE = "Dispose",
  GET_PHYSICAL_DEVICE_ID = "Get Physical Device ID",

  // Embedded Wallet Commands
  ASSIGN_WALLET = "Assign Wallet",
  CREATE_ACCOUNT = "Create Account",
  GET_ACCOUNTS = "Get Accounts",
  ADD_ASSET = "Add Asset",
  GET_ASSET = "Get Asset",
  GET_ASSETS = "Get Assets",
  GET_BALANCE = "Get Balance",
  GET_SUPPORTED_ASSETS = "Get Supported Assets",
  REFRESH_BALANCE = "Refresh Balance",
  GET_ADDRESSES = "Get Addresses",
  GET_DEVICE = "Get Device",
  GET_LATEST_BACKUP = "Get Latest Backup",
  GET_NFT = "Get NFT",
  GET_OWNED_NFTS = "Get Owned NFTs",
  LIST_OWNED_ASSETS = "List Owned Assets",
  LIST_OWNED_COLLECTIONS = "List Owned Collections",
  CREATE_WEB3_CONNECTION = "Create Web3 Connection",
  GET_WEB3_CONNECTIONS = "Get Web3 Connections",
  REMOVE_WEB3_CONNECTION = "Remove Web3 Connection",
  SUBMIT_WEB3_CONNECTION = "Submit Web3 Connection",
  CREATE_TRANSACTION = "Create Transaction",
  CREATE_AND_SIGN_TRANSACTION = "Create And Sign Transaction",
  CREATE_TRANSACTION_BY_JSON = "Create Transaction (by free json input)",
  GET_LATEST_TRANSACTIONS = "Get Latest Transactions",
  CANCEL_TRANSACTION = "Cancel Transaction",
  ESTIMATE_TRANSACTION_FEE = "Estimate Transaction Fee",
  GET_TRANSACTION_BY_ID = "Get Transaction By ID",
  GET_TRANSACTIONS = "Get Transactions",
}

export enum CommandFlags {
  INIT = "--init",
  ENV = "--env",
}
